bootc: Remove install of shim/grub
This removes the workaround to bootc that installs shim and grub.

It also drops the manual copy of ukiboot efi files over the shim
files, replacing it instead with the new ukiboot-default-efi
subpackage that does the same. These files are now tracked by
the rpm database, so bootupd can find the correct component
that owns them, rather than finding shim.

This also adds a TODO-BOOTC because I was not able to remove
grub2 from the bootc builder image. It failed with:

```
Installed: grub.cfg
error: boot data installation failed: Installing static GRUB configs: Create grubenv: Create file boot/grub2/grubenv: Failed to find "/usr/bin/grub2-editenv"
error: Installing to filesystem: Installing bootloader: Failed to run command: Command {
    program: "bootupctl",
    args: [
        "bootupctl",
        "backend",
        "install",
        "--write-uuid",
        "--src-root",
        "/run/osbuild/mounts/ostree/deploy/default/deploy/4b68ee6dd57c10fb90e40c05f8ccf0004124825266fd76c5af7e931c63e4320b.0",
        "--device",
        "/dev/loop1",
        "/run/osbuild/mounts",
    ],
    create_pidfd: false,
}
```
However, this is not as problematic, because this grub will not be in the final image.

For aboot (which really should have no EFIs at all) bootupd fails if there is no shim, so we create a fake empty one

NOTE: This requires ukiboot 0.2.0-2 for the new ukiboot-default-efi
rpm.