Fix issues around install-rpms tests
- Switch to EPEL 10, which forces to use readline7 package instead of
  neofetch, which is no longer available in EPEL 10
- Use alternative EPEL repo URL, because on some network following error
  is thrown on the default URL:

  ```
  libdnf._error.Error: Failed to download metadata for repo 'epel': repomd.xml parser error: Parse error at line: 1 (xmlParseStartTag: invalid element name
  ```

Signed-off-by: Martin Perina <mperina@redhat.com>