Fix work around for rootless bootc-image-builder
We had a workaround for rootless container use, where instead
of running bootc-image-builder in a container it just ran a locally
available /usr/bin/bootc-image-builder.

However, this is causing issue when using auto-image-builder.sh,
where we get errors like:

```
Running: /usr/bin/bootc-image-builder --output /var/tmp/automotive-image-builder-70mme_t8 --build-container localhost/aib-build:autosd10 --progress verbose --type raw quay.io/pchibon/ces2026:ride4_sa8775p_sx_r3 --store /var/tmp/automotive-image-builder-70mme_t8/store --rpmmd /var/tmp/automotive-image-builder-70mme_t8/rpmmd
Generating manifest manifest-raw.json
Manifest generation step
2026/03/04 14:06:40 error: cannot build manifest: failed to run bootc install print-configuration: exit status 125, output:
Running: rm -rf /var/tmp/automotive-image-builder-70mme_t8
ERROR: bootc-image-builder failed to create the image
```

I'm not sure exactly what is causing this atm, but lets fix this by:
 * Rename the bootc-image-builder in the aib container so oldeer aibs don't use it
 * Change the workaround in aib to look for the new name
 * Only use the workaround for the specific case of a rootless container (as it seems problemantic otherwise)